.model flat, C
.code
extern mProcs:DWORD
GetFileVersionInfoA_wrapper proc
	jmp mProcs[0*4]
GetFileVersionInfoA_wrapper endp
GetFileVersionInfoByHandle_wrapper proc
	jmp mProcs[1*4]
GetFileVersionInfoByHandle_wrapper endp
GetFileVersionInfoExA_wrapper proc
	jmp mProcs[2*4]
GetFileVersionInfoExA_wrapper endp
GetFileVersionInfoExW_wrapper proc
	jmp mProcs[3*4]
GetFileVersionInfoExW_wrapper endp
GetFileVersionInfoSizeA_wrapper proc
	jmp mProcs[4*4]
GetFileVersionInfoSizeA_wrapper endp
GetFileVersionInfoSizeExA_wrapper proc
	jmp mProcs[5*4]
GetFileVersionInfoSizeExA_wrapper endp
GetFileVersionInfoSizeExW_wrapper proc
	jmp mProcs[6*4]
GetFileVersionInfoSizeExW_wrapper endp
GetFileVersionInfoSizeW_wrapper proc
	jmp mProcs[7*4]
GetFileVersionInfoSizeW_wrapper endp
GetFileVersionInfoW_wrapper proc
	jmp mProcs[8*4]
GetFileVersionInfoW_wrapper endp
VerFindFileA_wrapper proc
	jmp mProcs[9*4]
VerFindFileA_wrapper endp
VerFindFileW_wrapper proc
	jmp mProcs[10*4]
VerFindFileW_wrapper endp
VerInstallFileA_wrapper proc
	jmp mProcs[11*4]
VerInstallFileA_wrapper endp
VerInstallFileW_wrapper proc
	jmp mProcs[12*4]
VerInstallFileW_wrapper endp
VerLanguageNameA_wrapper proc
	jmp mProcs[13*4]
VerLanguageNameA_wrapper endp
VerLanguageNameW_wrapper proc
	jmp mProcs[14*4]
VerLanguageNameW_wrapper endp
VerQueryValueA_wrapper proc
	jmp mProcs[15*4]
VerQueryValueA_wrapper endp
VerQueryValueW_wrapper proc
	jmp mProcs[16*4]
VerQueryValueW_wrapper endp
end