#pragma once


#include "Serialization/enumFactory.h"
#define ENUM_AS_MACRO_EnumParkourAction(XX) \
    XX(unk0, = 0) \
    XX(stumbleAtEdge_mb, = 1) \
    XX(slideUnder2, = 2) \
    XX(stepDownSmallHeight_mb, = 3) \
    XX(leapBeamToVShape, = 4) \
    XX(fromVshapeSmallStepDown, = 5) \
    XX(fromSlopeRiseToGround, = 6) \
    XX(unk7, = 7) \
    XX(stepDownWaistHeight_mb, = 8) \
    XX(riseFromGroundToGround_smallDiff_alsoVault9, = 9) \
    XX(passementFromBeam_A, = 10) \
    XX(fromGroundVaultThroughVShape, = 11) \
    XX(passementFromBeam_C, = 12) \
    XX(passementD, = 13) \
    XX(riseFromGroundToGround_smallDiff_alsoVault14, = 14) \
    XX(jumpDownToGround_airtimeButSafe, = 15) \
    XX(unk16, = 16) \
    XX(wallEjectToHang, = 17) /* The only place I found where a parkour action of this type is created is 14014BDEB, which doesn't seem to be a "reachable code path" in an unmodded game */ \
    XX(breakfall, = 18) \
    XX(unk19, = 19) \
    XX(freefallLedgeLandOn, = 20) \
    XX(breakfall21, = 21) \
    XX(unk22, = 22) \
    XX(fromHangToWallUpSameDepth_mb, = 23) \
    XX(unk24, = 24) \
    XX(unk25, = 25) \
    XX(fromHangToWall_side, = 26) \
    XX(fromHangToWallingUpAndTurnCornerOutside, = 27) /* 822.00 331.89 -0.17 Corner of a balcony: triggers fairly reliably if hold Left+Up */ \
    XX(hangTurnCornerInside, = 28) /* 16.99 -261.68 14.70 */ \
    XX(hangTurnCornerOutside, = 29) \
    XX(unk30, = 30) \
    XX(hangToDropDown_safe, = 31) \
    XX(riseFromHang, = 32) \
    XX(moveToSideWhileStillHanging, = 33) \
    XX(hangTurn_22, = 34) \
    XX(jumpAndGrabFrontWall, = 35) \
    XX(offTheWall_fromWallToGroundReleaseOrEject, = 36) \
    XX(fromGroundToLadder_up, = 37) \
    XX(runOffGroundEdgeAndGrabSideWall, = 38) \
    XX(climbFacade_fromWallDescentSidewaysToGround_alsoSidehop, = 39) \
    XX(dive, = 40) \
    XX(leapOffBuildingIntoUncontrolledFall_mb, = 41) \
    XX(leapOfFaithIntoWaterViaParkourUp, = 42) \
    XX(swing_2B, = 43) \
    XX(riseFromHangHP_mb, = 44) \
    XX(swingTurn_2D, = 45) \
    XX(swingToWalling_front, = 46) \
    XX(swing_2F_SwingToSidewall_includingSpindescent, = 47) \
    XX(swing_30_fromSwingToFeet, = 48) \
    XX(swing_31_swingToSwing_mb, = 49) \
    XX(offTheWall_fromWallToWallEjectAndCatch, = 50) \
    XX(unk51, = 51) \
    XX(wallrunUpFromGroundFailed_mb, = 52) \
    XX(wallrunUpFromGround_mb, = 53) \
    XX(wallrunUpToHang, = 54) \
    XX(fromSlopeRiseToWall, = 55) \
    XX(slideUnder56, = 56) \
    XX(plainStepDownToHang, = 57) \
    XX(fromSlopeSlideToHang, = 58) \
    XX(outOfWindowToHang_almostFellOutOfWindow, = 59) \
    XX(stepDownFromBeamToWall_mb, = 60) \
    XX(fromGroundToLadder_down, = 61) \
    XX(fromSlopeToWall_side_mb___UNABLE_TO_TRIGGER, = 62) /* 24.62 -218.43 25.49; 12.03 -244.42 28.11; - Actually looks decent if I force them at these locations. */ \
    XX(edgeDropBeforeFreeeFall_3F___UNABLE_TO_TRIGGER, = 63) /* 16.81 -260.32 16.01 */ \
    XX(fromGroundTurnAroundAndGrabWallParkourDown, = 64) \
    XX(onWallNormalClimb, = 65) \
    XX(unk66, = 66) \
    XX(climbCornerInside_onWallTurnCornerInner, = 67) \
    XX(onWallTurnCornerOuter, = 68) \
    XX(plainDismountFromWall_mb, = 69) \
    XX(fromWallToHang_down, = 70) \
    XX(fromWallToHang_side, = 71) \
    XX(fromWallingToHangDownAndTurnCornerOutside, = 72) /* 822.00 331.89 -0.17 Corner of a balcony: triggers fairly reliably if hold Right+Down */ \
    XX(climb_fromWallRiseToFeetOnLedge_49, = 73) \
    XX(unk74, = 74) \
    XX(riseToVShape, = 75) \
    XX(fromLadderToGround_up, = 76) \
    XX(fromWallToHang_up, = 77) \
    XX(fromHangToWall_down, = 78) \
    XX(backEject_4F, = 79) \
    XX(onLadderUpDown, = 80) \
    XX(unk81, = 81) \
    XX(unk82, = 82) \
    XX(unk83, = 83) \
    XX(unk84, = 84) \
    XX(unk85, = 85) \
    XX(choke_mb, = 86) \
    XX(unk87, = 87) \
    XX(unk88, = 88) \
    XX(unk89, = 89) \
    XX(unk90, = 90) \
    XX(unk91, = 91) \
    XX(unk92, = 92) \
    XX(unk93, = 93) \
    XX(unk94, = 94) \
    XX(unk95, = 95) \
    XX(unk96, = 96) \
    XX(fromWaterToWall, = 97) \
    XX(unk98, = 98) \
    XX(unk99, = 99) \
    XX(walkingOnBeamPassColumnAndContinue_R, = 100) \
    XX(walkingOnBeamPassColumnAndContinue_L, = 101) \
    XX(unk102, = 102) \
    XX(unk103, = 103) \
    XX(unk104, = 104) \
    XX(unk105, = 105) \
    XX(walkThroughWindow_mb_106, = 106) \
    XX(flipOverWindowLedgeToWalling, = 107) \
    XX(enterWindow, = 108) \
    XX(unk109, = 109) /* something like... flip over a fence, wallhang-to-wallhang-on-the-other-side. triggered by force-replacing "safe back eject" at [398.31 730.88 13.64] */\
    XX(unk110, = 110) \
    XX(unk111, = 111) \
    XX(leapOfFaith, = 112) \
    XX(unk113, = 113) \
    XX(passementFromHayStack, = 114) \
    XX(startJumpOutOfWindow, = 115) \
    XX(jumpOutOfWindowDescendToLedge_mb, = 116) /* Sprint out of window with ParkourUp at [497.08 125.68 9.92] */ \
    XX(unk117, = 117) \
    XX(unk118, = 118) \
    XX(jumpOutOfWindowToFeet, = 119) \
    XX(jumpOutOfWindowToWalling, = 120) \
    XX(jumpOutOfWindowToHang, = 121) \
    XX(defenestrateSprintOutOfWindow_122, = 122) \
    XX(jumpIntoWindow, = 123) \
    XX(unk124, = 124)


DECLARE_ENUM(EnumParkourAction, ENUM_AS_MACRO_EnumParkourAction)
