#pragma once


#include "ManagedObject.h"
#include "SharedPtr.h"
#include "Event.h"

class Entity;

class SharedPtrAndSmth
{
public:
    SharedPtrNew<Entity>* shared; //0x0000
    uint64 qword_8; //0x0008
    uint64 qword_10; //0x00010
}; //Size: 0x0018
assert_sizeof(SharedPtrAndSmth, 0x18);

class DangerEvent : public Event
{
public:
    enum SubType : uint32
    {
        SubType_Undefined = 0x4bd13e2e, // (CONFIRMED_NAME)
        SubType_SeePlayer = 0xf5d8f6b2, // (CONFIRMED_NAME)
        SubType_SeePlayerSneaking = 0xf72471c9, // (CONFIRMED_NAME)
        SubType_SeePlayerInWarningZone = 0x630d1301, // (CONFIRMED_NAME) RevValue: Unk_0x630d1301
        SubType_SeePlayerInHighAlertZone = 0x3f9c324b, // (CONFIRMED_NAME) RevValue: Unk_0x3f9c324b
        SubType_SeePlayerInAwareState = 0xc3fce2a2, // (CONFIRMED_NAME)
        SubType_SeePlayerInGuardPostWarningZone = 0xcecd5315, // (CONFIRMED_NAME)
        SubType_SeeFriendlyNPC = 0xb886805f, // (CONFIRMED_NAME)
        SubType_SeeOppositeGenderNPC = 0x5f9e1e37, // (CONFIRMED_NAME)
        SubType_SyncedAnimation = 0x72509d38, // (CONFIRMED_NAME)
        SubType_Alerted_EngageSuspect0 = 0xa9dd7729, // (CONFIRMED_NAME)
        SubType_Alerted_EngageSuspect1 = 0xdeda47bf, // (CONFIRMED_NAME)
        SubType_Alerted_EngageSuspect2 = 0x47d31605, // (CONFIRMED_NAME)
        SubType_Alerted_EngageSuspect3 = 0x30d42693, // (CONFIRMED_NAME)
        SubType_Awareness_StartNervous = 0x2a31f4db, // (CONFIRMED_NAME)
        SubType_Awareness_NPCNervous1 = 0xaea6adee, // (CONFIRMED_NAME)
        SubType_Awareness_NPCNervous2 = 0x37affc54, // (CONFIRMED_NAME)
        SubType_Awareness_NPCNervous3 = 0x40a8ccc2, // (CONFIRMED_NAME)
        SubType_Awareness_Yell1 = 0xefb98e8a, // (CONFIRMED_NAME)
        SubType_Awareness_Yell2 = 0x76b0df30, // (CONFIRMED_NAME)
        SubType_Awareness_Yell3 = 0x1b7efa6, // (CONFIRMED_NAME)
        SubType_Awareness_Accusation = 0x4268ce74, // (CONFIRMED_NAME)
        SubType_Awareness_StartDetective = 0xc2393aeb, // (CONFIRMED_NAME)
        SubType_Awareness_StopDetective = 0xba76c67f, // (CONFIRMED_NAME)
        SubType_Awareness_StartDetectiveArea = 0x24ca1a0f, // (CONFIRMED_NAME)
        SubType_Awareness_OngoingDetectiveArea = 0xc1dbef5, // (CONFIRMED_NAME)
        SubType_Awareness_ArrestGuard = 0x8327d3e6, // (CONFIRMED_NAME)
        SubType_Awareness_ArrestVictim = 0xde5bf33f, // (CONFIRMED_NAME)
        SubType_Awareness_UnfairAccusation = 0xfeb4f8b7, // (CONFIRMED_NAME)
        SubType_Awareness_MoveToLKP_Repulse = 0x620ebede, // (CONFIRMED_NAME)
        SubType_Scold = 0xfda03f6d, // (CONFIRMED_NAME)
        SubType_MildScold = 0x78c34c70, // (CONFIRMED_NAME)
        SubType_FactionInteraction_Step1 = 0x6aa4d62, // (CONFIRMED_NAME)
        SubType_FactionInteraction_Step2 = 0x9fa31cd8, // (CONFIRMED_NAME)
        SubType_FactionInteraction_Step3 = 0xe8a42c4e, // (CONFIRMED_NAME)
        SubType_FactionInteraction_Step2_Aborted = 0x2cc5d4a9, // (CONFIRMED_NAME)
        SubType_FactionInteraction_Step3_Aborted = 0x3bbec0ea, // (CONFIRMED_NAME)
        SubType_PlayerInRangeForTime = 0xcd8f80c3, // (CONFIRMED_NAME)
        SubType_MovingPlayerInRangeForTime = 0x21aaa829, // (CONFIRMED_NAME)
        SubType_SeeGuardPostPush = 0xcf2b37a4, // (CONFIRMED_NAME)
        SubType_Push = 0x26a88e30, // (CONFIRMED_NAME)
        SubType_Carrying_Dead_Body = 0x65cb773e, // (CONFIRMED_NAME)
        SubType_HeardGunFire = 0x4c175b6a, // (CONFIRMED_NAME)
        SubType_SeeGunFire = 0x6fe2075d, // (CONFIRMED_NAME)
        SubType_GunAim = 0x989fa186, // (CONFIRMED_NAME)
        SubType_GunFatal = 0xd1503d46, // (CONFIRMED_NAME)
        SubType_SeeGunAim = 0xd55dd7e5, // (CONFIRMED_NAME)
        SubType_SeeGunAimAt = 0xc46d4c1d, // (CONFIRMED_NAME)
        SubType_SeeGunFatal = 0x26e69ce9, // (CONFIRMED_NAME)
        SubType_SeePhantomBladeFatal = 0xfae498a7, // (CONFIRMED_NAME)
        SubType_SeePhantomBladeAimAt = 0x186f4853, // (CONFIRMED_NAME)
        SubType_GroundTackle = 0xa2fa821f, // (CONFIRMED_NAME)
        SubType_HitByBomb = 0xd4175637, // (CONFIRMED_NAME)
        SubType_ThrowingSmokeBomb = 0xc4e761df, // (CONFIRMED_NAME)
        SubType_ThrowingStunGrenade = 0xed2b2fd5, // (CONFIRMED_NAME)
        SubType_ThrowingMoneyPouch = 0x69dd0956, // (CONFIRMED_NAME)
        SubType_ThrowingPoisonBomb = 0x4367d157, // (CONFIRMED_NAME)
        SubType_ThrowingCherryBomb = 0x77cfc259, // (CONFIRMED_NAME)
        SubType_ThrowingProjectile = 0x25783c11, // (CONFIRMED_NAME)
        SubType_ThrowingProjectileFromCover = 0x7b49c53, // (CONFIRMED_NAME)
        SubType_SeeThrownObject = 0x51e41015, // (CONFIRMED_NAME)
        SubType_SeeShootSilentGun = 0x52e90974, // (CONFIRMED_NAME)
        SubType_SeeSilentGunKill = 0xc3b31f9, // (CONFIRMED_NAME)
        SubType_PlayerLanding = 0xc11502f6, // (CONFIRMED_NAME)
        SubType_PlayerLandingClose = 0x77b14422, // (CONFIRMED_NAME)
        SubType_SeePlayerInWater = 0xfecd3bbd, // (CONFIRMED_NAME)
        SubType_SeePlayerFallingInWater = 0x6167ccc9, // (CONFIRMED_NAME)
        SubType_WindowEntry = 0x8d29aba1, // (CONFIRMED_NAME)
        SubType_FightNonFatal = 0xc98ccc33, // (CONFIRMED_NAME)
        SubType_FightFatal = 0x3844191f, // (CONFIRMED_NAME)
        SubType_FightTarget = 0xb66028f3, // (CONFIRMED_NAME)
        SubType_FightOngoing = 0x65da91bb, // (CONFIRMED_NAME)
        SubType_Agonizing = 0x723c6315, // (CONFIRMED_NAME)
        SubType_IncomingAvoidableEntity = 0xe08320fc, // (CONFIRMED_NAME) RevValue: Unk_0xe08320fc
        SubType_RepulsionZone = 0x7455252b, // (CONFIRMED_NAME)
        SubType_IncomingPatrol = 0xac1e1c1f, // (CONFIRMED_NAME)
        SubType_IncomingBodyguards = 0x3fd728a8, // (CONFIRMED_NAME)
        SubType_ScatterCrowd = 0xdb4bb455, // (CONFIRMED_NAME)
        SubType_SmokeBombExplosion = 0xafd9d1b6, // (CONFIRMED_NAME)
        SubType_Money = 0xdba01491, // (CONFIRMED_NAME)
        SubType_MoneyGrabbed = 0x26dbe0d0, // (CONFIRMED_NAME)
        SubType_Fleeing = 0xf494a09e, // (CONFIRMED_NAME)
        SubType_CriminalFleeing = 0xbfefee03, // (CONFIRMED_NAME)
        SubType_Stumble = 0x5bcec023, // (CONFIRMED_NAME)
        SubType_Shove = 0xed8b7221, // (CONFIRMED_NAME)
        SubType_SeePlayerOnRooftop = 0x9f99125, // (CONFIRMED_NAME)
        SubType_SeePlayerInCover = 0x88f6a9a2, // (CONFIRMED_NAME)
        SubType_SeeDeadBody = 0x37be959a, // (CONFIRMED_NAME)
        SubType_SeeExpiredDeadBody = 0xcb336626, // (CONFIRMED_NAME)
        SubType_SeeNPCInIncapacitatedState = 0xcf1e7015, // (CONFIRMED_NAME)
        SubType_SeeExpiredNPCInIncapacitatedState = 0xbb77171b, // (CONFIRMED_NAME)
        SubType_SeePlayerInIncapacitatedState = 0xba83a5ef, // (CONFIRMED_NAME)
        SubType_SeeLootBody = 0x1ac12793, // (CONFIRMED_NAME)
        SubType_SeeLootObject = 0x16ea1385, // (CONFIRMED_NAME)
        SubType_SeePickpocket = 0xb22b46ce, // (CONFIRMED_NAME)
        SubType_WeaponUnsheath = 0xced6e477, // (CONFIRMED_NAME)
        SubType_WeaponUnsheathClose = 0x1c52f732, // (CONFIRMED_NAME)
        SubType_SeeArmedAssassin = 0x8315f5d1, // (CONFIRMED_NAME)
        SubType_SeeArmedAssassinClose = 0xddaeb4af, // (CONFIRMED_NAME)
        SubType_PhantomBladeUnsheath = 0x5e29005f, // (CONFIRMED_NAME)
        SubType_PhantomBladeUnsheathClose = 0x7b27fb6f, // (CONFIRMED_NAME)
        SubType_ParkourHighImpact = 0x21131e47, // (CONFIRMED_NAME)
        SubType_ParkourLowImpact = 0xa21eb834, // (CONFIRMED_NAME)
        SubType_ParkourHighImpactSound = 0xf1a540bf, // (CONFIRMED_NAME)
        SubType_ParkourLowImpactSound = 0x3fa1c4a2, // (CONFIRMED_NAME)
        SubType_PlayerSprint = 0x744137ca, // (CONFIRMED_NAME)
        SubType_HighProfileBeam = 0x7724353e, // (CONFIRMED_NAME)
        SubType_PlayerSwim = 0x2434c897, // (CONFIRMED_NAME)
        SubType_PlayerFastSwim = 0xe99487f8, // (CONFIRMED_NAME)
        SubType_LiftActivated = 0xba50eb95, // (CONFIRMED_NAME)
        SubType_AlertedOnRooftop = 0xd8ae5ed9, // (CONFIRMED_NAME)
        SubType_BrokenStructure = 0xee1a6ef6, // (CONFIRMED_NAME)
        SubType_ThiefAgression = 0x13760be6, // (CONFIRMED_NAME)
        SubType_StolenVictim = 0xa5465b1d, // (CONFIRMED_NAME)
        SubType_TackleThief = 0xb41b990c, // (CONFIRMED_NAME)
        SubType_KillMurderer = 0xabba101, // (CONFIRMED_NAME)
        SubType_CriminalThreatningVictim = 0xc17c1d8e, // (CONFIRMED_NAME)
        SubType_InnocentBeingInterrogated = 0xbaa63e1e, // (CONFIRMED_NAME)
        SubType_Scared = 0x445f3f1e, // (CONFIRMED_NAME)
        SubType_BegForMercy = 0xbfacf207, // (CONFIRMED_NAME)
        SubType_VerbalThreat = 0x7281aad1, // (CONFIRMED_NAME)
        SubType_MurdererKill = 0xa6c14474, // (CONFIRMED_NAME)
        SubType_CollectTaxes = 0x4815b427, // (CONFIRMED_NAME)
        SubType_Protesting = 0x8dc26d12, // (CONFIRMED_NAME)
        SubType_BeatUp = 0xc28485bc, // (CONFIRMED_NAME)
        SubType_Escorted = 0xa8f1e4ed, // (CONFIRMED_NAME)
        SubType_Execute = 0x334f64b1, // (CONFIRMED_NAME)
        SubType_Lockpicking = 0xfc1c98d5, // (CONFIRMED_NAME)
        SubType_SeeUnlockedDoor = 0x90815306, // (CONFIRMED_NAME)
        SubType_AlarmBell = 0x679cf21e, // (CONFIRMED_NAME)
        SubType_AlarmBellInZone = 0x2f2c6061, // (CONFIRMED_NAME)
        SubType_AlarmBellInZoneApproach = 0x67ac754b, // (CONFIRMED_NAME)
        SubType_SabotageAlarmBell = 0x402ce8bb, // (CONFIRMED_NAME)
        SubType_BellRingerWitnessSabotage = 0x54f214c3, // (CONFIRMED_NAME)
        SubType_TargettedByRangeWeapon = 0x9777902a, // (CONFIRMED_NAME)
        SubType_TargetingWithRangedWeapon = 0xfc2b79f2, // (CONFIRMED_NAME)
        SubType_IsHurtNonFatal = 0x8b240928, // (CONFIRMED_NAME)
        SubType_AssassinateFailed = 0xc7024a4e, // (CONFIRMED_NAME)
        SubType_AssassinateSurvived = 0x5a801714, // (CONFIRMED_NAME)
        SubType_IsHurt = 0x46b3eba2, // (CONFIRMED_NAME)
        SubType_IsHurtFromFar = 0xdd261b12, // (CONFIRMED_NAME)
        SubType_SmokeBombArround = 0xd420939b, // (CONFIRMED_NAME)
        SubType_AffectedBySmoke = 0xce54771b, // (CONFIRMED_NAME)
        SubType_AffectedBySmokeEnd = 0x24ba43d2, // (CONFIRMED_NAME)
        SubType_Death = 0x8b38d25b, // (CONFIRMED_NAME)
        SubType_Kill = 0x7ebbce3d, // (CONFIRMED_NAME)
        SubType_Assassinate = 0x89e1f3b1, // (CONFIRMED_NAME)
        SubType_AssassinateClose = 0x29d5afb8, // (CONFIRMED_NAME)
        SubType_StealthAssassinate = 0x9349d814, // (CONFIRMED_NAME)
        SubType_StealthAssassinateClose = 0x81676162, // (CONFIRMED_NAME)
        SubType_SeeCoverKill = 0xab73f37d, // (CONFIRMED_NAME)
        SubType_AssassinationNonLethal = 0x11e98206, // (CONFIRMED_NAME)
        SubType_AssassinationNonLethalClose = 0xef3aedef, // (CONFIRMED_NAME)
        SubType_AirAssassinate = 0xab3d3743, // (CONFIRMED_NAME)
        SubType_AirAssassinateClose = 0xc12f5fa0, // (CONFIRMED_NAME)
        SubType_Explosion = 0xc49a6f7d, // (CONFIRMED_NAME)
        SubType_NpcInWarningZone = 0x6fdfba1d, // (CONFIRMED_NAME)
        SubType_InterestPointLow = 0x4b1f9d0e, // (CONFIRMED_NAME)
        SubType_InterestPointHigh = 0xb7b5cdc9, // (CONFIRMED_NAME)
        SubType_InterestPointDangerSource = 0xd39cd718, // (CONFIRMED_NAME)
        SubType_IconicBladeImpact = 0x95071ee6, // (CONFIRMED_NAME)
        SubType_SuspiciousNoise = 0xe1c325e9, // (CONFIRMED_NAME)
        SubType_HSZInvestigation = 0x76691d39, // (CONFIRMED_NAME)
        SubType_BombSplashInWater = 0x3a588c7, // (CONFIRMED_NAME)
        SubType_PlayerMorphing = 0x441b1b95, // (CONFIRMED_NAME)
        SubType_Entertainer = 0xc6c040c6, // (CONFIRMED_NAME)
        SubType_Orator = 0x677d62a5, // (CONFIRMED_NAME)
        SubType_CallToInvestigate = 0x5d8f2282, // (CONFIRMED_NAME)
        SubType_DetectedTailer = 0x667c8a89, // (CONFIRMED_NAME)
        SubType_AlertTailVictim = 0x99f8d76f, // (CONFIRMED_NAME)
        SubType_AttractGuard = 0x90548b06, // (CONFIRMED_NAME)
        SubType_AttractAggressors = 0xbba3dde1, // (CONFIRMED_NAME)
        SubType_AttractProtectors = 0xd89ab1bd, // (CONFIRMED_NAME)
        SubType_FireCrackersAround = 0x96bd09e6, // (CONFIRMED_NAME)
        SubType_FireCrackersExplosion = 0xb0987e50, // (CONFIRMED_NAME)
        SubType_CherryBombAround = 0xa2204944, // (CONFIRMED_NAME)
        SubType_CherryBombExplosion = 0x14a35796, // (CONFIRMED_NAME)
        SubType_CherryBombExplosionClose = 0x2fcc7f07, // (CONFIRMED_NAME)
        SubType_TomatoBombAround = 0xb115ffff, // (CONFIRMED_NAME)
        SubType_TomatoBombExplosion = 0x39848b69, // (CONFIRMED_NAME)
        SubType_FlashbangAround = 0xe44c6840, // (CONFIRMED_NAME)
        SubType_FlashbangExplosion = 0xdb31c79c, // (CONFIRMED_NAME)
        SubType_MoneyPouchAround = 0x211b3335, // (CONFIRMED_NAME)
        SubType_MoneyPouchExplosion = 0x254b2d2a, // (CONFIRMED_NAME)
        SubType_MoneyPouchExplosionClose = 0x9fd55c40, // (CONFIRMED_NAME)
        SubType_PoisonGasAround = 0x2ceb711e, // (CONFIRMED_NAME)
        SubType_PoisonGasExplosion = 0x6ea15bbd, // (CONFIRMED_NAME)
        SubType_NPCPoisonned = 0x2624d172, // (CONFIRMED_NAME)
        SubType_NPCPoisonedEnd = 0xea465426, // (CONFIRMED_NAME)
        SubType_PoisonGasDissipated = 0xc1c9d616, // (CONFIRMED_NAME)
        SubType_ContagiousCharacterAround = 0x6be2816d, // (CONFIRMED_NAME)
        SubType_StunGrenadeAround = 0x481170bd, // (CONFIRMED_NAME)
        SubType_StunGrenadeExplosion = 0xf1ec92a3, // (CONFIRMED_NAME)
        SubType_NPCStunned = 0xbbbd0bf6, // (CONFIRMED_NAME)
        SubType_NPCStunnedEnd = 0xdfdc6c72, // (CONFIRMED_NAME)
        Unk_0xe29e41cc = 0xe29e41cc,
        Unk_0x1f85096d = 0x1f85096d,
        SubType_Berserk = 0x66bd7e86, // (CONFIRMED_NAME)
        SubType_BerserkInfection = 0xe73a3dc3, // (CONFIRMED_NAME)
        SubType_SeeBerserking = 0xf975a39c, // (CONFIRMED_NAME)
        SubType_RiftZoneClosing = 0x2e7b02e1, // (CONFIRMED_NAME)
        SubType_Force_Accusation = 0x80d7d218, // (CONFIRMED_NAME)
        SubType_Force_Alerted = 0x766a9e73, // (CONFIRMED_NAME)
        SubType_Force_Arrest = 0x9733d607, // (CONFIRMED_NAME)
        SubType_Force_AvoidVehicle = 0x1305a678, // (CONFIRMED_NAME)
        SubType_Force_BeatUp = 0x589c9930, // (CONFIRMED_NAME)
        SubType_Force_BulkReaction = 0x1dcb97e1, // (CONFIRMED_NAME)
        SubType_Force_CartFlee = 0xd829ab98, // (CONFIRMED_NAME)
        SubType_Force_CLRLookAt = 0x1b938d99, // (CONFIRMED_NAME)
        SubType_Force_Curious = 0x49969c02, // (CONFIRMED_NAME)
        SubType_Force_Dazed = 0xe9e95c27, // (CONFIRMED_NAME)
        SubType_Force_Distracted = 0x214a2469, // (CONFIRMED_NAME)
        SubType_Force_Fight = 0xea7a79a2, // (CONFIRMED_NAME)
        SubType_Force_Flee = 0xea183702, // (CONFIRMED_NAME)
        SubType_Force_Follow = 0xd22fa248, // (CONFIRMED_NAME)
        SubType_Force_GrabMoney = 0x408665c7, // (CONFIRMED_NAME)
        SubType_Force_MoveAway = 0xa644d3b0, // (CONFIRMED_NAME)
        SubType_Force_PushTarget = 0xdf0299b8, // (CONFIRMED_NAME)
        SubType_Force_Shoot = 0xbb94c14a, // (CONFIRMED_NAME)
        SubType_Force_Watch = 0x9bdb77d2, // (CONFIRMED_NAME)
        SubType_Force_Yell = 0x45ad48a9, // (CONFIRMED_NAME)
        SubType_Force_RepulsionZone = 0xcd9abace, // (CONFIRMED_NAME)
        SubType_Force_WatchCommotion = 0xe481f41c, // (CONFIRMED_NAME)
        SubType_Force_WatchCommotionClose = 0xa43112ec, // (CONFIRMED_NAME)
        SubType_Force_ForceCheering = 0xf798b027, // (CONFIRMED_NAME)
        SubType_Force_ForceStumble = 0xb590652b, // (CONFIRMED_NAME)
        SubType_Force_ForceShock = 0xfcd38742, // (CONFIRMED_NAME)
        SubType_Force_FireStarted = 0x32111099, // (CONFIRMED_NAME)
        SubType_GuillotineCutHead = 0x20f3ee64, // (CONFIRMED_NAME)
        SubType_PlaneFiring = 0x716c5706, // (CONFIRMED_NAME)
        SubType_RiftTornado = 0x9f5ce005, // (CONFIRMED_NAME)
        SubType_SeePlayer_Disguise_As_Agressor = 0x5a4f3d59, // (CONFIRMED_NAME)
        SubType_SeePlayer_Disguise_As_Protector = 0x6f21098d, // (CONFIRMED_NAME)
        SubType_SeePlayer_Disguise_As_Ally = 0x4c164d39, // (CONFIRMED_NAME)
        SubType_SeePlayer_Disguise_As_Civilian = 0x857dfec0, // (CONFIRMED_NAME)
        Unk_0x914af458 = 0x914af458,
        SubType_DynamicReaction = 0xbaf2ec7f, // (CONFIRMED_NAME)
        Unk_0xf85dac19 = 0xf85dac19,
        Unk_0xf5ac3e14 = 0xf5ac3e14,
        Unk_0xbd13f450 = 0xbd13f450,
        Unk_0xa60d3310 = 0xa60d3310,
        Unk_0x1340678d = 0x1340678d,
        Unk_0xbded328c = 0xbded328c,
        Unk_0x50896f87 = 0x50896f87,
        Unk_0x0064fc10 = 0x64fc10,
        Unk_0x0c748b8f = 0xc748b8f,
        Unk_0x89247d7a = 0x89247d7a,
        Unk_0x25ac2312 = 0x25ac2312,
        Unk_0x5ff1c6de = 0x5ff1c6de,
        SubType_MAX = 0x7dbcd6ea, // (CONFIRMED_NAME)
    };

    SharedPtrAndSmth witnessWhoPlayer; //0x0010
    SharedPtrAndSmth witnessByWhomNPC; //0x0028
    SubType responseHash; //0x0040
    uint32 dword_44; //0x0044
}; //Size: 0x0048
assert_sizeof(DangerEvent, 0x48);
