#pragma once

#include "basic_types.h"


enum class HUDModules : uint32
{
	HUDModules_Puppeteer = 0,
	HUDModules_Equipment = 1,
	HUDModules_Minimap = 2,
	HUDModules_HealthBar = 3,
	HUDModules_QuickSelection = 4,
	HUDModules_Icons = 5,
	HUDModules_MissionState = 6,
	HUDModules_MissionBriefing = 7,
	HUDModules_MissionRecap = 8,
	HUDModules_CriticalMessage = 9,
	HUDModules_ProximityMeter = 10,
	HUDModules_Message = 11,
	HUDModules_AFS = 12,
	HUDModules_LocalPlayerWidget = 13,
	HUDModules_RemotePlayerWidget = 14,
	HUDModules_ControlsLegend = 15,
	HUDModules_DateTimeLocationInformation = 16,
	HUDModules_HudItemDescription = 17,
	HUDModules_HudTitle = 18,
	HUDModules_StopFight = 19,
	HUDModules_Currencies = 20,
	HUDModules_RiftRelayHack = 21,
	HUDModules_MiniQuestLog = 22,
	HUDModules_Timer = 23,
	HUDModules_Subtitle = 24,
	HUDModules_ComTool = 25,
	HUDModules_Marker = 26,
	HUDModules_Weapon = 27,
	HUDModules_RiftHackerText = 28,
	HUDModules_LetterReader = 29,
	HUDModules_QuickTimeEvents = 30,
	HUDModules_ContextualInteraction = 31,
	HUDModules_CharacterPresentation = 32,
	HUDModules_Conflict = 33,
	HUDModules_InGameMapIcon = 34,
	HUDModules_TCR = 35,
	HUDModules_Loot = 36,
	HUDModules_CoopBriefing = 37,
	HUDModules_TrophyDisplay = 38,
	HUDModules_LockPick = 39,
	HUDModules_MouseCursor = 40,
	HUDModules_PeerPlayerIcons = 41,
	HUDModules_TrophyPreview = 42,
	HUDModules_TrophyCollection = 43,
	HUDModules_Tutorial = 44,
	HUDModules_NodePanel = 45,
	HUDModules_VillaStatus = 46,
	HUDModules_NotifyPC = 47,
	HUDModules_EliseLetters = 48,
	HUDModules_PlayerProfile = 49,
	HUDModules_Customization = 50,
	HUDModules_VillaQuest = 51,
	HUDModules_Costume = 52,
	HUDModules_VillaChest = 53,
	HUDModules_HighGround = 54,
	HUDModules_ClubSpaceProfile = 55,
	HUDModules_ClubSpaceObjective = 56,
	HUDModules_ClubSpaceCompetition = 57,
	HUDModules_EnablerWidget = 58,
	HUDModules_MyContact = 59,
	HUDModules_RiftValueHUD = 60,
	HUDModules_SkipCinematic = 61,
	HUDModules_AmbientGhost = 62,
	HUDModules_BlackBox = 63,
	HUDModules_AssassinsRank = 64,
	HUDModules_Awareness = 65,
	HUDModules_Count = 66,
};
