#include "pch.h"

#include "ACU/CLAssassin.h"
#include "ACU/BhvAssassin.h"
#include "ACU/CharacterAI.h"
#include "ACU/ACUGetSingletons.h"

CLAssassin* CLAssassin::GetSingleton()
{
    BhvAssassin* bhv = ACU::GetPlayerBhvAssassin();
    if (!bhv) { return nullptr; }
    CharacterAI* charAI = bhv->characterAI_toHealthAndInventory;
    if (!charAI) { return nullptr; }

    // I don't understand the mechanics of Statecharts, but I believe their connecting code
    // was autogenerated somehow from some node trees.
    // These offsets below were retrieved at 142032D60, when the result of that function was a `CLAssassin`.
    constexpr int kindaHardcodedOffset1 = 2;
    constexpr int kindaHardcodedOffset2 = 0;
    Statechart* step1 = charAI->childStatecharts_mb_toHealth_60[kindaHardcodedOffset1];
    if (!step1) { return nullptr; }
    Statechart* step2 = step1->childStatecharts_mb_toHealth_60[kindaHardcodedOffset2];
    if (!step2) { return nullptr; }
    return static_cast<CLAssassin*>(step2);
}
